services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: mem1
      DB_PASSWORD: 123
      DB_NAME: GRAPHIC
      HOST_NAME: localhost
      PORT: 8050
      JWT_SECRET: 9Hv0b7XJJGwSpaZxRYd2bBuhFzw0PtLM
      JWT_EXPIRE: 1d
    ports:
      - "8050:8050"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql_network
    volumes:
      - .:/src/server
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: GRAPHIC
      MYSQL_USER: mem1
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init script
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

networks:
  mysql_network: